version: 5.1.0
variant: default
logo: /images/logo.png
head:
  favicon: /images/favicon.png
  manifest:
    name:
    short_name: blog
    start_url: https://blog.yang-hong-xin.com/
    theme_color: "#3273dc"
    background_color: "#3273dc"
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss: /atom.xml
navbar:
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: https://yang-hong-xin.com/me
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/jk195417/blog
footer:
  copyright: © 2023
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    GitHub:
      icon: fab fa-github
      url: https://github.com/jk195417/blog
article:
  highlight:
    theme: atom-one-dark
    clipboard: false
    fold: unfolded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
  index_pages: true
comment:
  type: disqus
  shortname: yang-hong-xin
donates:
  - type: buymeacoffee
    url: https://www.buymeacoffee.com/aaronyang
  - type: paypal
    business: jk195417@gmail.com
    currency_code: USD
share:
  type: sharethis
  install_url: https://platform-api.sharethis.com/js/sharethis.js#property=60d7d9bc0c52fc001291b96c&product=inline-share-buttons
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - position: left
    type: profile
    author: 楊竑昕
    author_title: Software Engineer
    location: 台中，台灣
    avatar:
    avatar_rounded: false
    gravatar: jk195417@gmail.com
    follow_link: https://github.com/jk195417
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/jk195417
      Facebook:
        icon: fab fa-facebook
        url: https://facebook.com/yang.hong.xin
      Linkedin:
        icon: fab fa-linkedin
        url: https://linkedin.com/in/hongxin-yang/
      Medium:
        icon: fab fa-medium
        url: https://medium.com/@yang.hong.xin
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: left
    type: links
    links:
      Resume: https://yang-hong-xin.com/me
      Master Thesis: https://hdl.handle.net/11296/gazcm2
  - position: left
    type: categories
  - position: left
    type: recent_posts
  - position: left
    type: archives
  - position: left
    type: tags
    order_by: name
    amount:
    show_count: true
  - position: left
    type: adsense
    client_id: ca-pub-6329280350982888
    slot_id: "9953995920"
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  bing_webmaster:
    tracking_id:
  busuanzi: false
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id: UA-117837845-1
  hotjar:
    site_id:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
